name: Build and Deploy Mentormate Backend & Frontend

on:
  push:
    branches: [main]

env:
  PROJECT_ID: protean-horizon-457804-v7
  REGION: us-central1
  SERVICE_ACCOUNT: mentormate-sa@protean-horizon-457804-v7.iam.gserviceaccount.com

jobs:
  deploy-backend:
    name: Deploy Backend with DB ENV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/mentormate-backend ./backend
          docker push gcr.io/${{ env.PROJECT_ID }}/mentormate-backend

      - name: Deploy Backend to Cloud Run with .env
        run: |
          gcloud run deploy mentormate-sa \
            --image gcr.io/${{ env.PROJECT_ID }}/mentormate-backend \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ env.SERVICE_ACCOUNT }} \
            --set-env-vars "NODE_ENV=production,DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},JWT_SECRET=${{ secrets.JWT_SECRET }}"
  
#   deploy-frontend:
#     name: Deploy Frontend
#     runs-on: ubuntu-latest
#     needs: deploy-backend

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Authenticate with GCP
#         uses: google-github-actions/auth@v1
#         with:
#           credentials_json: '${{ secrets.GCP_SA_KEY }}'

#       - name: Setup Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ env.PROJECT_ID }}

#       - name: Configure Docker
#         run: gcloud auth configure-docker

#       - name: Build and Push Frontend Docker Image
#         run: |
#           docker build -t gcr.io/${{ env.PROJECT_ID }}/mentormate-frontend ./frontend
#           docker push gcr.io/${{ env.PROJECT_ID }}/mentormate-frontend

#       - name: Deploy Frontend to Cloud Run
#         run: |
#           gcloud run deploy mentormate-frontend \
#             --image gcr.io/${{ env.PROJECT_ID }}/mentormate-frontend \
#             --region ${{ env.REGION }} \
#             --platform managed \
#             --allow-unauthenticated \
#             --service-account ${{ env.SERVICE_ACCOUNT }}
