name: Deploy Frontend to Cloud Run

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]

env:
  PROJECT_ID: protean-horizon-457804-v7
  SERVICE_NAME: mentormate-frontend
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      working-directory: frontend
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated \
          --service-account mentormate-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
